Server:
  ContextPath: /
  Port: 8080
  ReadTimeoutSec: 10
  WriteTimeoutSec: 10
  GracefulShutdownTimeoutSec: 10
Grpc:
  Port: 3000  
  GracefulShutdownTimeoutSec: 10
Logging:
  Level: debug
Database:
  Driver: mysql
  Name: chitchat
  Host: localhost
  Port: 3306
  Username: root
  Password: callicoder 
Migration:
  Path: file://db/migrations    
Auth:
  JwtSecret: secret
  JwtExpiryInSec: 2592000
  GoogleClientId: 351329348566-7ugi3mja9tbghse8ub1cfmuhupeb8h70.apps.googleusercontent.com
