Server:
  ContextPath: /
  Port: 8080
  ReadTimeoutSec: 10
  WriteTimeoutSec: 10
  GracefulShutdownTimeoutSec: 10
Grpc:
  Port: 3000  
  GracefulShutdownTimeoutSec: 10
Logging:
  Level: debug
Database:
  DriverName: mysql
  URL: mysql://root:callicoder@/test?charset=utf8   
Migration:
  Path: file://db/migrations    
Auth:
  JwtSecret: secret
  JwtExpiryInSec: 2592000
